# Generated by Django 4.1.5 on 2023-01-21 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customusercreation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUserCreation',
        ),
    ]
