# Generated by Django 4.1.5 on 2023-01-26 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='project',
        ),
    ]
