# Generated by Django 4.1.5 on 2023-01-27 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='comment',
            field=models.TextField(),
        ),
    ]
