# Generated by Django 4.1.5 on 2023-01-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_alter_pledge_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
