# Generated by Django 4.1.5 on 2023-01-27 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_alter_comment_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
