# Generated by Django 4.1.5 on 2023-01-28 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0025_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='liked_by',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_projects', to='projects.category', to_field='name'),
        ),
        migrations.AddField(
            model_name='project',
            name='favourite_by',
            field=models.ManyToManyField(related_name='favourite_by_projects', through='projects.Favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
