# Generated by Django 4.1.5 on 2023-01-28 15:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0026_remove_project_liked_by_project_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.RemoveField(
            model_name='project',
            name='favourite_by',
        ),
        migrations.AddField(
            model_name='project',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
