# Generated by Django 4.1.5 on 2023-01-29 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_remove_project_category_remove_project_favourite_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
