# Generated by Django 4.1.5 on 2023-01-30 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='liked_by',
        ),
    ]
