# Generated by Django 4.1.5 on 2023-01-30 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_comment_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='liked_by',
        ),
    ]
