# Generated by Django 4.1.5 on 2023-01-30 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_remove_comment_liked_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='comment_author',
        ),
    ]
