# Generated by Django 4.1.5 on 2023-01-30 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_rename_author_comment_comment_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_author',
            new_name='author',
        ),
    ]
