# Generated by Django 4.1.5 on 2023-02-18 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0040_remove_comment_author_comment_commentor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commentor',
        ),
        migrations.AddField(
            model_name='comment',
            name='commentator',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='commentator_comment', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
