# Generated by Django 4.1.5 on 2023-02-28 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0043_pledge_date_pledged_alter_project_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='liked_by',
        ),
    ]
