# Generated by Django 4.1.5 on 2023-02-28 14:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0044_remove_project_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='liked_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
